name = "metalify"
compatibility_date = "2024-03-05"

[vars]
NUXT_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "metalify-db"
database_id = "1c11661e-6c3f-48f6-9c33-dbb754b076d5"

[env.production]
workers_dev = true